const express = require('express');
const app = express();

app.get('/api', (req, res) => {
  const data = {
    jerseyNumber: [4, 10, 8, 15, 3, 9, 7, 14, 3, 1, 11, 12],
    height: [
      '6-0',
      '6-3',
      '6-10',
      '6-8',
      '5-11',
      '6-4',
      '6-8',
      '6-6',
      '5-8',
      '6-0',
      '6-10',
      '6-7',
    ],
    weight: [190, 205, 235, 215, 184, 210, 225, 220, 179, 200, 230, 225],
    players: [
      'playerOne',
      'playerTwo',
      'playerThree',
      'playerFour',
      'playerOne',
      'playerTwo',
      'playerThree',
      'playerFour',
      'playerOne',
      'playerTwo',
      'playerThree',
      'playerFour',
    ],
    points: [
      '16.3',
      '26.1',
      '7.7',
      '4.4',
      '16.3',
      '26.1',
      '7.7',
      '4.4',
      '16.3',
      '26.1',
      '7.7',
      '4.4',
    ],
    assists: [
      '9.6',
      '3.2',
      '4.1',
      '2.2',
      '6.2',
      '4.1',
      '2.2',
      '3.2',
      '7.1',
      '2.2',
      '3.2',
      '4.1',
    ],
    rebounds: [
      '1.6',
      '4.3',
      '12.1',
      '8.2',
      '1.6',
      '4.3',
      '12.1',
      '8.2',
      '1.6',
      '4.3',
      '12.1',
      '8.2',
    ],
    position: [
      'PG',
      'SG',
      'C',
      'PF',
      'PG',
      'SG',
      'C',
      'PF',
      'PG',
      'SG',
      'C',
      'PF',
    ],
    // playing: [
    //   {
    //     active: true,
    //     active: true,
    //     active: true,
    //     active: false,
    //     active: true,
    //     active: true,
    //     active: true,
    //     active: false,
    //     active: true,
    //   },
    // ],
  };
  res.json(data);
});

app.listen(5000);
